### ISSUE TITLE
Frequency rather than proportion

### ISSUE THREAD

**Issue by trvrb** [blab/ncov-forecasting-fit#15]
When you reference absolute error, either in the text or in a figure or table, please use frequency (eg 10%) rather than proportion (eg 0.1). Right now in Table 1 it's hard to immediately know whether the top left entry is supposed to be 0.9% or 0.009%. For this, please update:
* Table 1
* Figure 2A (Figure 2B is good)
* y-axes in all panels of Figure 4
* y-axes in panels B and C of Figure 5
to use frequency notation.

**Comment by trvrb** [comment]
This was successfully completed for everything except Figure 4. Please update `Var_of_interest.png` to use frequency rather than proportion on all 5 panels.

**Comment by trvrb** [comment]
This was successfully completed for everything except Figure 4. Please update `Var_of_interest.png` to use frequency rather than proportion on all 5 panels.

**Comment by Eabousam** [comment]
Pushed updated and reran figure with frequencies and updated label
