### ISSUE TITLE
Include supplementary version of Figure 1 with other 4 countries

### ISSUE THREAD

**Issue by trvrb** [blab/ncov-forecasting-fit#18]
In general, I'm a huge fan of the Tufte maxim to "Above All Else Show the Data". Directly showing model outputs compared to "truth" in Figure 1 is illuminating. Here, just "showing the data" was especially helpful to me for thinking about mean vs median summary.

Please make a new Supplementary Figure 1 that is exactly like current Figure 1 with panel A of data and panel B of forecasts, except rather than Japan and the US, instead show Australia, Brazil, South Africa and the United Kingdom. Version this in `manuscript/figures/` and call it something like `Dynamic_est_env_supp.png`.

**Comment by Eabousam** [comment]
Created supp figure 1, made a supplementary figure file, and added figure 1 supp
