### ISSUE TITLE
Swap from GARW to MLR for Figure 1

### ISSUE THREAD

**Issue by trvrb** [blab/ncov-forecasting-fit#19]
In Figure 1, you currently use GARW as the model for panel B. I would recommend changing this to MLR. You use MLR when diving into results in Figure 3, Figure 4 and Figure 5. It feels off at the moment having Figure 1 be GARW and the later figures be MLR.

Following https://github.com/blab/ncov-forecasting-fit/issues/18, please make the supplemental figure 1 with Australia, Brazil, South Africa and the UK also use MLR rather than GARW.

**Comment by Eabousam** [comment]
Changed model used to MLR and created supplementary figure 1
