### ISSUE TITLE
Drop panel B in Figure 3

### ISSUE THREAD

**Issue by trvrb** [blab/ncov-forecasting-fit#20]
Results from panel B in Figure 3 (variant frequency at observation vs median growth advantage) [were never referenced in the text](https://github.com/blab/ncov-forecasting-fit/blob/467a887d50e8015c7c0260f1a378f4d2ad8f723a/manuscript/ncov-forecasting-fit.tex#L256).

I would recommend dropping Figure 3B entirely. The only thing I take from this is that there is no real relationship between variant frequency at observation and median growth advantage. There is certainly not stabilization. You can see wide swings in growth advantage even after hitting 10% frequency. Better to just focus on Figure 3A, which makes intuitive sense and tells you what you need to know for this point.

**Comment by Eabousam** [comment]
Figure 3B Dropped
