### ISSUE TITLE
Figure 4B correlation

### ISSUE THREAD

**Issue by trvrb** [blab/ncov-forecasting-fit#26]
In commit f0207d393a30125b24646f92cb7e441516ff39e5 the _R_ correlation coefficient for proportion bad QC in Figure 4B went from 0.22 to 0.01. What's going on here?

This is good reason why informative commit messages are helpful. I can't interpret "updating figure 4". This is also why updating figure specific `.ipynb` along with updating PNGs is helpful.

**Comment by Eabousam** [comment]
Yes I'll make sure to write out the commit, the reason the R went down is because we decided on using the Mean AE instead of the median here

**Comment by Eabousam** [comment]
Fixed issue and reran all data and figures for var of interest

**Comment by Eabousam** [comment]
Yes, 0.01 result comes from filtering the lead == 30 instead of lead == 0.
