### ISSUE TITLE
Semantic figure names

### ISSUE THREAD

**Issue by trvrb** [blab/ncov-forecasting-fit#7]
I'd very much suggest using semantic names for figures in LaTeX manuscript. You want to be able to shuffle figures around and move between main text and supplement. It gets confusing if the files have names like `Figure2.png`. Take a look here for an example of how I approached this: 
- Figures: https://github.com/trvrb/flux/tree/master/figures
- References in `.tex`: https://github.com/trvrb/flux/blob/master/flux.tex#L279

**Comment by Eabousam** [comment]
I finished renaming the figures and cleaned the file to only have the final ones.

**Comment by trvrb** [comment]
Awesome! I see these changes in https://github.com/blab/ncov-forecasting-fit/commit/36b066cda6651dc2e7e52e9f446831e34ca40824. If you update `table1.png`, I think this issue can be closed.
